#!/usr/bin/env ansible-playbook
---
- name: Setup Kubernetes bootstrap node
  hosts: bootstrap_node
  gather_facts: false
  become: true
  vars:
    cilium_version: "1.18.0"
  tasks:
    - name: Get bootstrap node IP details
      setup:
        gather_subset:
          - default_ipv4

    - name: Set cluster name
      set_fact:
        cluster_name: '{{ inventory_hostname }}'

    - name: Pull control plane images
      command: kubeadm config images pull
      changed_when: false # idempotent

    - name: Send over kubeadm config file
      template:
        src: kubeadm-init.yaml
        dest: /var/tmp/kubeadm-init.yaml

    - name: Initialize Kubernetes (mark-control-plane phase)
      shell: "kubeadm init --config /var/tmp/kubeadm-init.yaml > /var/log/kubeadm-init-output.log"
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Wait for port to be ready
      wait_for:
        host: 127.0.0.1
        port: 6443
        delay: 5

    - name: Install Cilium to cluster
      command: "cilium install --version {{ cilium_version }}"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      args:
        creates: /etc/cni/net.d/05-cilium.conflist

    - name: Wait for Cilium installation to complete
      command: "cilium status --wait"
      changed_when: false # idempotent
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Get cluster join command for worker nodes
      command: kubeadm token create --print-join-command
      changed_when: false # idempotent
      register: join_cmd_output

    - name: Set cluster join command as host fact
      set_fact:
        worker_join_command: "{{ join_cmd_output.stdout }}"

- name: Join worker nodes to cluster
  hosts: worker_nodes
  gather_facts: false
  become: true
  tasks:
    - name: Set cluster facts
      set_fact:
        cluster_name: "{{ hostvars[groups['bootstrap_node'][0]]['cluster_name'] }}"
        cluster_address: "{{ hostvars[groups['bootstrap_node'][0]]['ansible_facts']['default_ipv4']['address'] }}"
        cluster_join_command: "{{ hostvars[groups['bootstrap_node'][0]]['worker_join_command'] }}"

    - name: Add hosts entry for cluster name
      lineinfile:
        path: /etc/hosts
        search_string: '{{ cluster_address }}'
        line: '{{ cluster_address }} {{ cluster_name }}'

    - name: Join cluster as worker node
      command: '{{ cluster_join_command }}'
      args:
        creates: /etc/kubernetes/kubelet.conf
