---
#
# Install runc
# 
- name: Download runc
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.{{ node_arch }}
    checksum: "sha256:https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.sha256sum"
    dest: /usr/local/sbin/runc
    mode: 0755
