---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
apiServer:
  extraArgs:
  - name: anonymous-auth
    value: "true"
networking:
  serviceSubnet: "{{ service_network_cidr }}"
  podSubnet: "{{ pod_network_cidr }}"
...
