---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
apiServer:
  extraArgs:
  - name: anonymous-auth
    value: "true"
  certSANs:
    - "{{ cluster_name }}"
    - "127.0.1.1"
    - "127.0.0.1"
clusterName: "{{ cluster_name }}"
controlPlaneEndpoint: "{{ cluster_name }}:6443"
...
