---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
apiServer:
  extraArgs:
  - name: anonymous-auth
    value: "true"
  certSANs:
    - "{{ cluster_name }}.local"
    - "127.0.1.1"
    - "127.0.0.1"
networking:
  serviceSubnet: "{{ service_network_cidr }}"
  podSubnet: "{{ pod_network_cidr }}"
clusterName: "{{ cluster_name }}"
controlPlaneEndpoint: "{{ cluster_name }}.local:6443"
...
