---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  bindPort: {{ control_plane_listen_port }}
...
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
apiServer:
  extraArgs:
  - name: anonymous-auth
    value: "true"
  - name: secure-port
    value: "{{ control_plane_listen_port }}"
{% if control_plane_endpoint_alternative_names | length > 0 %}
  certSANs:
{% for alternative_name in control_plane_endpoint_alternative_names %}
    - "{{ alternative_name }}"
{% endfor %}
{% endif %}
controlPlaneEndpoint: "{{ control_plane_endpoint_name }}"
networking:
  serviceSubnet: "{{ service_network_cidr }}"
  podSubnet: "{{ pod_network_cidr }}"
...