---
- name: Ensure that keepalived variables are defined
  assert:
    that:
      - keepalived_router_id is defined
      - keepalived_virtual_address is defined
      - keepalived_cluster_password is defined

- name: Find the first network interface for keepalived
  shell: find /sys/class/net/ -type l -name enp* -print -quit | xargs basename
  register: interface_result

- name: Set fact with the keepalived interface
  set_fact:
    keepalived_interface: "{{ interface_result.stdout | trim }}"

- name: Install keeaplived
  apt:
    name: keepalived
    state: present

- name: Enable keepalived service
  service:
    name: keepalived
    enabled: yes

- name: Send over check_port.sh script
  copy:
    src: check_port.sh
    dest: /etc/keepalived/check_port.sh
    mode: 0755

- name: Set keepalived priority
  set_fact:
    keepalived_priority: "{{ 200 if node_type == 'bootstrap_node' else 100 }}"

- name: Send keepalived.conf
  template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf

- name: restart keepalived
  service:
    name: keepalived
    state: restarted