---
- name: Wait for the file to appear
  wait_for:
    path: /data/shared/.control-plane-join
    timeout: 300
  register: wait_result

- name: Fail if the file did not appear in time
  fail:
    msg: "File did not appear within the 300s timeout period."
  when: not wait_result.elapsed

- name: Read the file contents
  slurp:
    src: /data/shared/.control-plane-join
  register: join_command

- name: Decode the file contents
  set_fact:
    script_content: "{{ join_command.content | b64decode | trim }}"

- name: Execute the file as a shell script
  shell: |
    {{ script_content }} --apiserver-bind-port {{ control_plane_listen_port }}
  args:
    executable: /bin/bash