---
- name: Wait for the file to appear
  wait_for:
    path: "{{ cluster_filesystem_path }}/.worker-node-join"
    delay: 3
    timeout: 300
  register: wait_result

- name: Fail if the file did not appear in time
  fail:
    msg: "File did not appear within the 300s timeout period."
  when: wait_result.elapsed >= 300

- name: Read the file contents
  slurp:
    src: "{{ cluster_filesystem_path }}/.worker-node-join"
  register: join_command

- name: Decode the file contents
  set_fact:
    script_content: "{{ join_command.content | b64decode | trim }}"

- name: Execute the file as a shell script
  shell: |
    {{ script_content }}
  args:
    executable: /bin/bash